export interface Student {
  id: string;
  name: string;
  initials: string;
  avatarBg: string;
  studentId: string;
  gender: 'Male' | 'Female';
  dob: string;
  nationality: string;
  email: string;
  phone: string;
  parentName: string;
  parentEmail: string;
  busRoute: string;
  medicalNotes: string;
  attendance: number;
  gpa: number;
  gpaHistory: { term: string; gpa: number }[];
  attendanceHistory: { month: string; rate: number }[];
  subjects: { name: string; grade: string; score: number }[];
  behaviorLogs: { date: string; type: string; note: string; severity: 'info' | 'warning' | 'danger' }[];
  achievements: { title: string; date: string; icon: string }[];
  status: 'On Track' | 'Monitor' | 'At Risk' | 'Critical';
}

export const STUDENTS: Student[] = [
  {
    id: 'stu-43178',
    name: 'Evelyn Harper',
    initials: 'EH',
    avatarBg: '#7c3aed',
    studentId: 'PRE43178',
    gender: 'Female',
    dob: '12/03/2008',
    nationality: 'British',
    email: 'e.harper@olympiaschools.edu',
    phone: '+971 50 123 4567',
    parentName: 'Margaret Harper',
    parentEmail: 'm.harper@gmail.com',
    busRoute: 'Route 7 - Al Barsha',
    medicalNotes: 'Mild asthma — inhaler in school clinic',
    attendance: 78,
    gpa: 2.85,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.10 }, { term: 'Yr9 T2', gpa: 3.05 }, { term: 'Yr9 T3', gpa: 2.95 },
      { term: 'Yr10 T1', gpa: 3.20 }, { term: 'Yr10 T2', gpa: 3.00 }, { term: 'Yr10 T3', gpa: 2.88 },
      { term: 'Yr11 T1', gpa: 2.85 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 92 }, { month: 'Sep', rate: 78 }, { month: 'Oct', rate: 80 },
      { month: 'Nov', rate: 75 }, { month: 'Dec', rate: 82 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'C', score: 68 },
      { name: 'English A HL', grade: 'B', score: 74 },
      { name: 'Physics SL', grade: 'C', score: 65 },
      { name: 'Chemistry SL', grade: 'B', score: 72 },
      { name: 'History HL', grade: 'B', score: 76 },
      { name: 'Literature HL', grade: 'C', score: 67 },
    ],
    behaviorLogs: [
      { date: '09/05/2026', type: 'Absence', note: '3 consecutive unexcused absences — parent contacted', severity: 'danger' },
      { date: '02/04/2026', type: 'Late Arrival', note: 'Arrived 25 minutes late — noted in register', severity: 'warning' },
    ],
    achievements: [
      { title: 'Science Fair Participant', date: 'Mar 2026', icon: '🔬' },
      { title: 'Perfect Attendance — Term 1 Yr10', date: 'Dec 2024', icon: '🏅' },
    ],
    status: 'At Risk',
  },
  {
    id: 'stu-43180',
    name: 'Oliver Pemberton',
    initials: 'OP',
    avatarBg: '#0891b2',
    studentId: 'PRE43180',
    gender: 'Male',
    dob: '05/07/2008',
    nationality: 'Australian',
    email: 'o.pemberton@olympiaschools.edu',
    phone: '+971 52 234 5678',
    parentName: 'Daniel Pemberton',
    parentEmail: 'd.pemberton@outlook.com',
    busRoute: 'Route 3 - JBR',
    medicalNotes: 'No known conditions',
    attendance: 97,
    gpa: 3.88,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.60 }, { term: 'Yr9 T2', gpa: 3.72 }, { term: 'Yr9 T3', gpa: 3.75 },
      { term: 'Yr10 T1', gpa: 3.80 }, { term: 'Yr10 T2', gpa: 3.82 }, { term: 'Yr10 T3', gpa: 3.85 },
      { term: 'Yr11 T1', gpa: 3.88 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 100 }, { month: 'Sep', rate: 97 }, { month: 'Oct', rate: 98 },
      { month: 'Nov', rate: 96 }, { month: 'Dec', rate: 97 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'A', score: 92 },
      { name: 'English A HL', grade: 'A', score: 89 },
      { name: 'Physics SL', grade: 'A', score: 91 },
      { name: 'Chemistry SL', grade: 'A', score: 88 },
      { name: 'History HL', grade: 'A', score: 90 },
      { name: 'Literature HL', grade: 'B', score: 84 },
    ],
    behaviorLogs: [],
    achievements: [
      { title: 'Academic Excellence Award', date: 'Jun 2025', icon: '🏆' },
      { title: 'Student Council President', date: 'Sep 2025', icon: '⭐' },
      { title: 'Math Olympiad — 2nd Place', date: 'Feb 2026', icon: '🥈' },
    ],
    status: 'On Track',
  },
  {
    id: 'stu-43201',
    name: 'Marcus Chen',
    initials: 'MC',
    avatarBg: '#0f766e',
    studentId: 'PRE43201',
    gender: 'Male',
    dob: '22/11/2007',
    nationality: 'Singaporean',
    email: 'm.chen@olympiaschools.edu',
    phone: '+971 55 345 6789',
    parentName: 'Linda Chen',
    parentEmail: 'linda.chen@gmail.com',
    busRoute: 'Route 5 - DIFC',
    medicalNotes: 'Lactose intolerant',
    attendance: 85,
    gpa: 3.10,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.30 }, { term: 'Yr9 T2', gpa: 3.25 }, { term: 'Yr9 T3', gpa: 3.18 },
      { term: 'Yr10 T1', gpa: 3.22 }, { term: 'Yr10 T2', gpa: 3.15 }, { term: 'Yr10 T3', gpa: 3.12 },
      { term: 'Yr11 T1', gpa: 3.10 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 90 }, { month: 'Sep', rate: 85 }, { month: 'Oct', rate: 83 },
      { month: 'Nov', rate: 87 }, { month: 'Dec', rate: 85 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'B', score: 78 },
      { name: 'English A HL', grade: 'B', score: 75 },
      { name: 'Physics SL', grade: 'B', score: 76 },
      { name: 'Chemistry SL', grade: 'C', score: 70 },
      { name: 'History HL', grade: 'B', score: 79 },
      { name: 'Literature HL', grade: 'B', score: 74 },
    ],
    behaviorLogs: [
      { date: '15/04/2026', type: 'Late Submission', note: 'History essay submitted 2 days late', severity: 'warning' },
    ],
    achievements: [
      { title: 'Debate Club — Finalist', date: 'Apr 2026', icon: '🎤' },
    ],
    status: 'Monitor',
  },
  {
    id: 'stu-43215',
    name: 'Sophia Nakamura',
    initials: 'SN',
    avatarBg: '#be185d',
    studentId: 'PRE43215',
    gender: 'Female',
    dob: '14/06/2008',
    nationality: 'Japanese',
    email: 's.nakamura@olympiaschools.edu',
    phone: '+971 50 456 7890',
    parentName: 'Kenji Nakamura',
    parentEmail: 'k.nakamura@yahoo.co.jp',
    busRoute: 'Route 2 - Downtown',
    medicalNotes: 'Severe nut allergy — EpiPen in clinic',
    attendance: 82,
    gpa: 2.95,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.40 }, { term: 'Yr9 T2', gpa: 3.25 }, { term: 'Yr9 T3', gpa: 3.10 },
      { term: 'Yr10 T1', gpa: 3.05 }, { term: 'Yr10 T2', gpa: 2.98 }, { term: 'Yr10 T3', gpa: 2.92 },
      { term: 'Yr11 T1', gpa: 2.95 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 88 }, { month: 'Sep', rate: 82 }, { month: 'Oct', rate: 80 },
      { month: 'Nov', rate: 84 }, { month: 'Dec', rate: 82 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'C', score: 66 },
      { name: 'English A HL', grade: 'B', score: 75 },
      { name: 'Physics SL', grade: 'D', score: 58 },
      { name: 'Chemistry SL', grade: 'C', score: 64 },
      { name: 'History HL', grade: 'B', score: 73 },
      { name: 'Literature HL', grade: 'C', score: 69 },
    ],
    behaviorLogs: [
      { date: '08/05/2026', type: 'Absence', note: 'Medical leave — 4 days, documentation received', severity: 'warning' },
      { date: '10/03/2026', type: 'Academic Concern', note: 'Physics exam score below passing threshold', severity: 'danger' },
    ],
    achievements: [
      { title: 'Art Exhibition — Featured Work', date: 'Jan 2026', icon: '🎨' },
    ],
    status: 'At Risk',
  },
  {
    id: 'stu-43229',
    name: 'Aiden Okafor',
    initials: 'AO',
    avatarBg: '#15803d',
    studentId: 'PRE43229',
    gender: 'Male',
    dob: '30/09/2007',
    nationality: 'Nigerian',
    email: 'a.okafor@olympiaschools.edu',
    phone: '+971 54 567 8901',
    parentName: 'Chukwuemeka Okafor',
    parentEmail: 'c.okafor@gmail.com',
    busRoute: 'Route 9 - Mirdif',
    medicalNotes: 'No known conditions',
    attendance: 89,
    gpa: 3.22,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.10 }, { term: 'Yr9 T2', gpa: 3.15 }, { term: 'Yr9 T3', gpa: 3.20 },
      { term: 'Yr10 T1', gpa: 3.18 }, { term: 'Yr10 T2', gpa: 3.22 }, { term: 'Yr10 T3', gpa: 3.20 },
      { term: 'Yr11 T1', gpa: 3.22 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 92 }, { month: 'Sep', rate: 89 }, { month: 'Oct', rate: 91 },
      { month: 'Nov', rate: 88 }, { month: 'Dec', rate: 89 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'B', score: 79 },
      { name: 'English A HL', grade: 'A', score: 85 },
      { name: 'Physics SL', grade: 'B', score: 80 },
      { name: 'Chemistry SL', grade: 'B', score: 78 },
      { name: 'History HL', grade: 'B', score: 82 },
      { name: 'Literature HL', grade: 'A', score: 86 },
    ],
    behaviorLogs: [],
    achievements: [
      { title: 'Community Service Award', date: 'May 2026', icon: '💛' },
    ],
    status: 'Monitor',
  },
  {
    id: 'stu-43244',
    name: 'Leila Rostami',
    initials: 'LR',
    avatarBg: '#b45309',
    studentId: 'PRE43244',
    gender: 'Female',
    dob: '18/02/2008',
    nationality: 'Iranian',
    email: 'l.rostami@olympiaschools.edu',
    phone: '+971 56 678 9012',
    parentName: 'Farideh Rostami',
    parentEmail: 'f.rostami@hotmail.com',
    busRoute: 'Route 4 - Jumeirah',
    medicalNotes: 'Anxiety disorder — counselor aware',
    attendance: 76,
    gpa: 2.70,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.20 }, { term: 'Yr9 T2', gpa: 3.00 }, { term: 'Yr9 T3', gpa: 2.88 },
      { term: 'Yr10 T1', gpa: 2.80 }, { term: 'Yr10 T2', gpa: 2.75 }, { term: 'Yr10 T3', gpa: 2.72 },
      { term: 'Yr11 T1', gpa: 2.70 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 85 }, { month: 'Sep', rate: 76 }, { month: 'Oct', rate: 72 },
      { month: 'Nov', rate: 78 }, { month: 'Dec', rate: 74 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'D', score: 55 },
      { name: 'English A HL', grade: 'C', score: 68 },
      { name: 'Physics SL', grade: 'D', score: 52 },
      { name: 'Chemistry SL', grade: 'C', score: 65 },
      { name: 'History HL', grade: 'C', score: 67 },
      { name: 'Literature HL', grade: 'C', score: 70 },
    ],
    behaviorLogs: [
      { date: '07/05/2026', type: 'Absence', note: 'Recurring absences — parent meeting scheduled', severity: 'danger' },
      { date: '20/04/2026', type: 'Academic Concern', note: 'Math and Physics below passing threshold', severity: 'danger' },
      { date: '05/03/2026', type: 'Counselor Referral', note: 'Referred to school counselor — anxiety support', severity: 'warning' },
    ],
    achievements: [],
    status: 'Critical',
  },
  {
    id: 'stu-43258',
    name: 'Noah Fitzgerald',
    initials: 'NF',
    avatarBg: '#1d4ed8',
    studentId: 'PRE43258',
    gender: 'Male',
    dob: '07/12/2007',
    nationality: 'Irish',
    email: 'n.fitzgerald@olympiaschools.edu',
    phone: '+971 50 789 0123',
    parentName: 'Patrick Fitzgerald',
    parentEmail: 'p.fitzgerald@gmail.com',
    busRoute: 'Route 6 - Marina',
    medicalNotes: 'No known conditions',
    attendance: 98,
    gpa: 3.75,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.50 }, { term: 'Yr9 T2', gpa: 3.55 }, { term: 'Yr9 T3', gpa: 3.60 },
      { term: 'Yr10 T1', gpa: 3.65 }, { term: 'Yr10 T2', gpa: 3.70 }, { term: 'Yr10 T3', gpa: 3.72 },
      { term: 'Yr11 T1', gpa: 3.75 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 100 }, { month: 'Sep', rate: 98 }, { month: 'Oct', rate: 97 },
      { month: 'Nov', rate: 99 }, { month: 'Dec', rate: 98 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'A', score: 88 },
      { name: 'English A HL', grade: 'A', score: 90 },
      { name: 'Physics SL', grade: 'A', score: 87 },
      { name: 'Chemistry SL', grade: 'A', score: 85 },
      { name: 'History HL', grade: 'A', score: 91 },
      { name: 'Literature HL', grade: 'A', score: 89 },
    ],
    behaviorLogs: [],
    achievements: [
      { title: 'English Essay Competition — 1st Place', date: 'Mar 2026', icon: '✍️' },
      { title: 'Perfect Attendance Term 1', date: 'Dec 2025', icon: '🏅' },
    ],
    status: 'On Track',
  },
  {
    id: 'stu-43271',
    name: 'Amara Diallo',
    initials: 'AD',
    avatarBg: '#9d174d',
    studentId: 'PRE43271',
    gender: 'Female',
    dob: '25/04/2008',
    nationality: 'Senegalese',
    email: 'a.diallo@olympiaschools.edu',
    phone: '+971 52 890 1234',
    parentName: 'Ibrahim Diallo',
    parentEmail: 'i.diallo@yahoo.fr',
    busRoute: 'Route 8 - Deira',
    medicalNotes: 'No known conditions',
    attendance: 95,
    gpa: 3.55,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.30 }, { term: 'Yr9 T2', gpa: 3.38 }, { term: 'Yr9 T3', gpa: 3.42 },
      { term: 'Yr10 T1', gpa: 3.45 }, { term: 'Yr10 T2', gpa: 3.50 }, { term: 'Yr10 T3', gpa: 3.52 },
      { term: 'Yr11 T1', gpa: 3.55 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 96 }, { month: 'Sep', rate: 95 }, { month: 'Oct', rate: 94 },
      { month: 'Nov', rate: 96 }, { month: 'Dec', rate: 95 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'B', score: 82 },
      { name: 'English A HL', grade: 'A', score: 87 },
      { name: 'Physics SL', grade: 'B', score: 80 },
      { name: 'Chemistry SL', grade: 'B', score: 83 },
      { name: 'History HL', grade: 'A', score: 88 },
      { name: 'Literature HL', grade: 'A', score: 86 },
    ],
    behaviorLogs: [],
    achievements: [
      { title: 'Model UN — Best Delegate', date: 'Apr 2026', icon: '🌍' },
    ],
    status: 'On Track',
  },
  {
    id: 'stu-43285',
    name: 'Luca Marchetti',
    initials: 'LM',
    avatarBg: '#c2410c',
    studentId: 'PRE43285',
    gender: 'Male',
    dob: '11/08/2007',
    nationality: 'Italian',
    email: 'l.marchetti@olympiaschools.edu',
    phone: '+971 55 901 2345',
    parentName: 'Giorgio Marchetti',
    parentEmail: 'g.marchetti@gmail.com',
    busRoute: 'Route 1 - Abu Hail',
    medicalNotes: 'No known conditions',
    attendance: 93,
    gpa: 3.40,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.20 }, { term: 'Yr9 T2', gpa: 3.25 }, { term: 'Yr9 T3', gpa: 3.30 },
      { term: 'Yr10 T1', gpa: 3.32 }, { term: 'Yr10 T2', gpa: 3.36 }, { term: 'Yr10 T3', gpa: 3.38 },
      { term: 'Yr11 T1', gpa: 3.40 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 95 }, { month: 'Sep', rate: 93 }, { month: 'Oct', rate: 92 },
      { month: 'Nov', rate: 94 }, { month: 'Dec', rate: 93 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'B', score: 81 },
      { name: 'English A HL', grade: 'B', score: 79 },
      { name: 'Physics SL', grade: 'B', score: 83 },
      { name: 'Chemistry SL', grade: 'B', score: 80 },
      { name: 'History HL', grade: 'B', score: 78 },
      { name: 'Literature HL', grade: 'B', score: 82 },
    ],
    behaviorLogs: [],
    achievements: [
      { title: 'Sports Day — 400m Winner', date: 'Feb 2026', icon: '🏃' },
    ],
    status: 'On Track',
  },
  {
    id: 'stu-43299',
    name: 'Zara Al-Mansouri',
    initials: 'ZA',
    avatarBg: '#6d28d9',
    studentId: 'PRE43299',
    gender: 'Female',
    dob: '03/01/2008',
    nationality: 'Emirati',
    email: 'z.almansouri@olympiaschools.edu',
    phone: '+971 50 012 3456',
    parentName: 'Khalid Al-Mansouri',
    parentEmail: 'k.almansouri@eim.ae',
    busRoute: 'Route 10 - Sharjah',
    medicalNotes: 'No known conditions',
    attendance: 99,
    gpa: 3.92,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: 3.70 }, { term: 'Yr9 T2', gpa: 3.75 }, { term: 'Yr9 T3', gpa: 3.80 },
      { term: 'Yr10 T1', gpa: 3.82 }, { term: 'Yr10 T2', gpa: 3.88 }, { term: 'Yr10 T3', gpa: 3.90 },
      { term: 'Yr11 T1', gpa: 3.92 },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: 100 }, { month: 'Sep', rate: 99 }, { month: 'Oct', rate: 100 },
      { month: 'Nov', rate: 98 }, { month: 'Dec', rate: 99 },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: 'A', score: 95 },
      { name: 'English A HL', grade: 'A', score: 93 },
      { name: 'Physics SL', grade: 'A', score: 94 },
      { name: 'Chemistry SL', grade: 'A', score: 92 },
      { name: 'History HL', grade: 'A', score: 96 },
      { name: 'Literature HL', grade: 'A', score: 91 },
    ],
    behaviorLogs: [],
    achievements: [
      { title: 'Top of Class — Term 1', date: 'Dec 2025', icon: '🥇' },
      { title: 'National Science Olympiad — Finalist', date: 'Mar 2026', icon: '🔭' },
      { title: 'Head Girl', date: 'Sep 2025', icon: '👑' },
    ],
    status: 'On Track',
  },
];

// Fill remaining students to 25
const EXTRA_NAMES = [
  { name: 'James Thornton', initials: 'JT', bg: '#0369a1', nat: 'British', status: 'On Track' as const, att: 96, gpa: 3.58 },
  { name: 'Priya Sharma', initials: 'PS', bg: '#7c3aed', nat: 'Indian', status: 'On Track' as const, att: 94, gpa: 3.45 },
  { name: 'Ethan Williams', initials: 'EW', bg: '#15803d', nat: 'American', status: 'Monitor' as const, att: 88, gpa: 3.12 },
  { name: 'Isabella Torres', initials: 'IT', bg: '#b45309', nat: 'Spanish', status: 'On Track' as const, att: 97, gpa: 3.68 },
  { name: 'Ryo Tanaka', initials: 'RT', bg: '#0f766e', nat: 'Japanese', status: 'On Track' as const, att: 99, gpa: 3.80 },
  { name: 'Fatima Al-Zahra', initials: 'FZ', bg: '#9d174d', nat: 'Moroccan', status: 'On Track' as const, att: 95, gpa: 3.52 },
  { name: 'Benjamin Scott', initials: 'BS', bg: '#1d4ed8', nat: 'Canadian', status: 'Monitor' as const, att: 87, gpa: 3.18 },
  { name: 'Chloe Dubois', initials: 'CD', bg: '#c2410c', nat: 'French', status: 'On Track' as const, att: 96, gpa: 3.65 },
  { name: 'Samuel Adeyemi', initials: 'SA', bg: '#6d28d9', nat: 'Nigerian', status: 'On Track' as const, att: 93, gpa: 3.48 },
  { name: 'Mei Lin Zhang', initials: 'MZ', bg: '#be185d', nat: 'Chinese', status: 'On Track' as const, att: 98, gpa: 3.78 },
  { name: 'Carlos Mendoza', initials: 'CM', bg: '#0891b2', nat: 'Mexican', status: 'On Track' as const, att: 92, gpa: 3.35 },
  { name: 'Anya Petrov', initials: 'AP', bg: '#7c3aed', nat: 'Russian', status: 'Monitor' as const, att: 86, gpa: 3.08 },
  { name: 'David Kim', initials: 'DK', bg: '#15803d', nat: 'Korean', status: 'On Track' as const, att: 97, gpa: 3.70 },
  { name: 'Nadia Hassan', initials: 'NH', bg: '#b45309', nat: 'Egyptian', status: 'On Track' as const, att: 94, gpa: 3.55 },
  { name: 'Lucas Andersen', initials: 'LA', bg: '#0369a1', nat: 'Danish', status: 'On Track' as const, att: 98, gpa: 3.82 },
];

EXTRA_NAMES.forEach((s, i) => {
  const idx = i + 11;
  STUDENTS.push({
    id: `stu-${43300 + i}`,
    name: s.name,
    initials: s.initials,
    avatarBg: s.bg,
    studentId: `PRE${43300 + i}`,
    gender: i % 2 === 0 ? 'Male' : 'Female',
    dob: `${(i % 28) + 1}/${(i % 12) + 1}/2008`,
    nationality: s.nat,
    email: `${s.name.split(' ')[0].toLowerCase()}.${s.name.split(' ')[1].toLowerCase()}@olympiaschools.edu`,
    phone: `+971 5${i % 6} ${100 + i * 7} ${200 + i * 13}`,
    parentName: `Parent of ${s.name}`,
    parentEmail: `parent.${s.name.split(' ')[1].toLowerCase()}@gmail.com`,
    busRoute: `Route ${(i % 10) + 1}`,
    medicalNotes: i % 5 === 0 ? 'No known conditions noted' : 'No known conditions',
    attendance: s.att,
    gpa: s.gpa,
    gpaHistory: [
      { term: 'Yr9 T1', gpa: s.gpa - 0.20 },
      { term: 'Yr9 T2', gpa: s.gpa - 0.15 },
      { term: 'Yr9 T3', gpa: s.gpa - 0.12 },
      { term: 'Yr10 T1', gpa: s.gpa - 0.08 },
      { term: 'Yr10 T2', gpa: s.gpa - 0.05 },
      { term: 'Yr10 T3', gpa: s.gpa - 0.02 },
      { term: 'Yr11 T1', gpa: s.gpa },
    ],
    attendanceHistory: [
      { month: 'Aug', rate: s.att + 2 },
      { month: 'Sep', rate: s.att },
      { month: 'Oct', rate: s.att - 1 },
      { month: 'Nov', rate: s.att + 1 },
      { month: 'Dec', rate: s.att },
    ],
    subjects: [
      { name: 'Mathematics HL', grade: s.gpa >= 3.6 ? 'A' : s.gpa >= 3.0 ? 'B' : 'C', score: Math.round(s.gpa * 24) },
      { name: 'English A HL', grade: s.gpa >= 3.6 ? 'A' : s.gpa >= 3.0 ? 'B' : 'C', score: Math.round(s.gpa * 23) },
      { name: 'Physics SL', grade: s.gpa >= 3.6 ? 'A' : s.gpa >= 3.0 ? 'B' : 'C', score: Math.round(s.gpa * 23) },
      { name: 'Chemistry SL', grade: s.gpa >= 3.6 ? 'A' : s.gpa >= 3.0 ? 'B' : 'C', score: Math.round(s.gpa * 22) },
      { name: 'History HL', grade: s.gpa >= 3.6 ? 'A' : s.gpa >= 3.0 ? 'B' : 'C', score: Math.round(s.gpa * 24) },
      { name: 'Literature HL', grade: s.gpa >= 3.6 ? 'A' : s.gpa >= 3.0 ? 'B' : 'C', score: Math.round(s.gpa * 23) },
    ],
    behaviorLogs: [],
    achievements: [],
    status: s.status,
  });
});